### ISSUE TITLE
Messages not transmitting between clients

### ISSUE THREAD

**Issue by Thorzdad2** [KodeNet/statuspage#1]
I have two Adium clients. They both can see when each other join the network. They can see their statuses change throughout the day. They can see when the other one is writing a message. But, no messages are transmitted. This behavior began last week. Up until then messaging worked without issue. No settings have been changed in the Adium clients.

**Comment by variablenix** [comment]
There have been a couple new changes due to the amount of spam advertisements.

1. OTR encryption is now **required** between all contacts
2. Contacts must be in each other's roster/buddy list; otherwise messages cannot be received

Before the changes, OTR was not required and anyone could just randomly message anyone. Unfortunately there has been an uptick in the amount of spam/advertisements, but now virtually reduced to none with the recent changes.

Can you try again?

**Comment by variablenix** [comment]
I removed OTR from being a requirement because it was actually not allowing MUC messages to go through. It should still be fine. I think the more crucial thing to help with spam is to make sure random strangers can't just message someone unless they're in the recipient's roster.

Thanks for the report.

**Comment by Thorzdad2** [comment]
Many thanks! Messaging on Adium is working great now.
